name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      # Build Seniors Daily News into site/data/news.json
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install feed deps
        run: pip install feedparser requests
      - name: Build news.json
        run: python bot/senior_news.py

      # Safety check: make sure the site has an index.html
      - name: Verify site folder
        run: |
          test -f site/index.html || (echo "::error::Missing site/index.html" && exit 1)
          touch site/.nojekyll
          echo "=== TREE (site) ==="; find site -maxdepth 2 -type f -print | sort
          echo "=== HEAD news.json ==="; head -n 25 site/data/news.json || true

      - uses: actions/configure-pages@v5
        with:
          enablement: true

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - id: deployment
        uses: actions/deploy-pages@v4
